#pragma once

#define COREOBJECT_NAMESPACE CoreObject

#define BEGIN_NAMESPACE_COREOBJECT BEGIN_NAMESPACE_KAYOU namespace COREOBJECT_NAMESPACE {
#define END_NAMESPACE_COREOBJECT } /* namespace COREOBJECT_NAMESPACE */ END_NAMESPACE_KAYOU