#pragma once

#define WINDOW_NAMESPACE Window

#define BEGIN_NAMESPACE_WINDOW BEGIN_NAMESPACE_KAYOU namespace WINDOW_NAMESPACE {
#define END_NAMESPACE_WINDOW } /* namespace WINDOW_NAMESPACE */ END_NAMESPACE_KAYOU