#pragma once

#define ASSETMANAGER_NAMESPACE AssetManager

#define BEGIN_NAMESPACE_ASSETMANAGER BEGIN_NAMESPACE_KAYOU namespace ASSETMANAGER_NAMESPACE {
#define END_NAMESPACE_ASSETMANAGER } /* namespace ASSETMANAGER_NAMESPACE */ END_NAMESPACE_KAYOU